config/routes.rb
Rails.application.routes.draw do
  resources :details
  resources :detalles

  get '/orders/doit/:id', to: 'orders#doit', as: 'doit'
  get '/orders/listaproductos/:id', to: 'orders#listaproductos', as: 'listaproductos'
  get '/ajaxorden', to: 'orders#listaproductos', as: 'ajaxorden'
  post '/orders/saveDetails', to: 'orders#saveDetails', as: 'saveDetails'
  resources :orders

  resources :categoria
  resources :empleados
  devise_for :users
  
  get '/recepcions/findCliente/:id', to: 'recepcions#findCliente', as: 'findCliente'
  resources :recepcions

  resources :cargos
  get "panel/index"

  root :to => "panel#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :mesas, :concerns => :paginatable
  resources :productos, :concerns => :paginatable

  resources :clientes









end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
	has_many :empleados
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :recepcions, :dependent => :destroy
end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
	validates :Qt_Cantidad, presence: true
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	belongs_to :cargo
	has_many :recepcions
	#validates :
	validates :Nu_Dni, :No_Empleado, :Tx_Direccion, :Co_Departamento, :Co_Provincia, :Co_Distrito, :Tx_Email, :Fe_Nacimiento, :Tx_telefono, :Fl_Sexo, :Fl_EstadoCivil, :Fe_Contrato, :Fe_Culminacion, :Sa_Salario, presence: true
	validates :Nu_Dni, numericality: { only_integer: true }, uniqueness: true, length: { maximum: 8 }, length: { minimum: 8 }
end
	#validates :equipo1, :equipo2, :arbitro, :estadio, presence: true
	#validates :equipo1, :equipo2, numericality: { only_integer: true }
	#validates :arbitro, :estadio, length: { minimum: 4 }

	#validates :nombre, presence: true, length: { in: 2..20 }, uniqueness: true
	#validates :ciudad, presence: true, length: { maximum: 100 }

app/models/mesa.rb
class Mesa < ActiveRecord::Base
	validates :Co_Mesa, :Qt_CantidadSillas, :Nu_Mesa, :Tipo_Mesa, presence: true
	validates :Co_Mesa, uniqueness: true
	validates :Tipo_Mesa, length: { minimum: 3}
	validates :Qt_CantidadSillas, :Nu_Mesa, numericality: { only_integer: true }
	has_many :recepcions, :dependent => :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :categorium
end

app/models/recepcion.rb
class Recepcion < ActiveRecord::Base
	belongs_to :empleado
	belongs_to :cliente
	belongs_to :mesa
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html
      format.pdf do
         #pdf = Prawn::Document.new
         pdf = ReportPdf.new(@clientes)
         send_data pdf.render, filename: 'report_cliente.pdf', type: 'application/pdf'
      end
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:Co_Cliente, :Nu_Dni, :No_Cliente, :Ape_Paterno, :Ape_Mateno, :Fe_Ingreso)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/recepcion_helper.rb
module RecepcionHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Co_Cliente %><br>
    <%= f.text_field :Co_Cliente %>
  </div>
  <div class="field">
    <%= f.label :Nu_Dni %><br>
    <%= f.text_field :Nu_Dni %>
  </div>
  <div class="field">
    <%= f.label :No_Cliente %><br>
    <%= f.text_field :No_Cliente %>
  </div>
  <div class="field">
    <%= f.label :Ape_Paterno %><br>
    <%= f.text_field :Ape_Paterno %>
  </div>
  <div class="field">
    <%= f.label :Ape_Mateno %><br>
    <%= f.text_field :Ape_Mateno %>
  </div>
  <div class="field">
    <%= f.label :Fe_Ingreso %><br>
    <%= f.date_select :Fe_Ingreso %>
  </div>
  <div class="actions">
    <% if params[:action] == 'new'%>
      <%= f.submit "Agregar cliente" %>
    <% else %>
      <%= f.submit "Actualizar datos del cliente" %>
    <% end %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Clientes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Apellido paterno</th>
      <th>Apellido mateno</th>
      <th>N° dni</th>
      <th>Fecha ingreso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.Co_Cliente %></td>
        <td><%= cliente.No_Cliente %></td>
        <td><%= cliente.Ape_Paterno %></td>
        <td><%= cliente.Ape_Mateno %></td>
        <td><%= cliente.Nu_Dni %></td>
        <td><%= cliente.Fe_Ingreso %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar Cliente', new_cliente_path %> ! <a href="/clientes.pdf">Imprimir Clientes</a>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form' %>

<%= link_to 'Regresar a la lista de clientes', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Co cliente:</strong>
  <%= @cliente.Co_Cliente %>
</p>

<p>
  <strong>Nu dni:</strong>
  <%= @cliente.Nu_Dni %>
</p>

<p>
  <strong>No cliente:</strong>
  <%= @cliente.No_Cliente %>
</p>

<p>
  <strong>Ape paterno:</strong>
  <%= @cliente.Ape_Paterno %>
</p>

<p>
  <strong>Ape mateno:</strong>
  <%= @cliente.Ape_Mateno %>
</p>

<p>
  <strong>Fe ingreso:</strong>
  <%= @cliente.Fe_Ingreso %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>