config/routes.rb
Rails.application.routes.draw do
  resources :details
  resources :detalles

  get '/orders/doit/:id', to: 'orders#doit', as: 'doit'
  get '/orders/listaproductos/:id', to: 'orders#listaproductos', as: 'listaproductos'
  get '/ajaxorden', to: 'orders#listaproductos', as: 'ajaxorden'
  post '/orders/saveDetails', to: 'orders#saveDetails', as: 'saveDetails'
  resources :orders

  resources :categoria
  resources :empleados
  devise_for :users
  
  get '/recepcions/findCliente/:id', to: 'recepcions#findCliente', as: 'findCliente'
  resources :recepcions

  resources :cargos
  get "panel/index"

  root :to => "panel#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :mesas, :concerns => :paginatable
  resources :productos, :concerns => :paginatable

  resources :clientes









end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
	has_many :empleados
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :recepcions, :dependent => :destroy
end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
	validates :Qt_Cantidad, presence: true
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	belongs_to :cargo
	has_many :recepcions
	#validates :
	validates :Nu_Dni, :No_Empleado, :Tx_Direccion, :Co_Departamento, :Co_Provincia, :Co_Distrito, :Tx_Email, :Fe_Nacimiento, :Tx_telefono, :Fl_Sexo, :Fl_EstadoCivil, :Fe_Contrato, :Fe_Culminacion, :Sa_Salario, presence: true
	validates :Nu_Dni, numericality: { only_integer: true }, uniqueness: true, length: { maximum: 8 }, length: { minimum: 8 }
end
	#validates :equipo1, :equipo2, :arbitro, :estadio, presence: true
	#validates :equipo1, :equipo2, numericality: { only_integer: true }
	#validates :arbitro, :estadio, length: { minimum: 4 }

	#validates :nombre, presence: true, length: { in: 2..20 }, uniqueness: true
	#validates :ciudad, presence: true, length: { maximum: 100 }

app/models/mesa.rb
class Mesa < ActiveRecord::Base
	validates :Co_Mesa, :Qt_CantidadSillas, :Nu_Mesa, :Tipo_Mesa, presence: true
	validates :Co_Mesa, uniqueness: true
	validates :Tipo_Mesa, length: { minimum: 3}
	validates :Qt_CantidadSillas, :Nu_Mesa, numericality: { only_integer: true }
	has_many :recepcions, :dependent => :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :categorium
end

app/models/recepcion.rb
class Recepcion < ActiveRecord::Base
	belongs_to :empleado
	belongs_to :cliente
	belongs_to :mesa
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:No_Cargo)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/recepcion_helper.rb
module RecepcionHelper
end

app/views/cargos/_form.html.erb
<%= form_for(@cargo) do |f| %>
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% @cargo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :No_Cargo %><br>
    <%= f.text_field :No_Cargo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cargos</h1>

<table>
  <thead>
    <tr>
      <th>No cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.No_Cargo %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No cargo:</strong>
  <%= @cargo.No_Cargo %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>