config/routes.rb
Rails.application.routes.draw do
  resources :details
  resources :detalles

  get '/orders/doit/:id', to: 'orders#doit', as: 'doit'
  get '/orders/listaproductos/:id', to: 'orders#listaproductos', as: 'listaproductos'
  get '/ajaxorden', to: 'orders#listaproductos', as: 'ajaxorden'
  post '/orders/saveDetails', to: 'orders#saveDetails', as: 'saveDetails'
  resources :orders

  resources :categoria
  resources :empleados
  devise_for :users
  
  get '/recepcions/findCliente/:id', to: 'recepcions#findCliente', as: 'findCliente'
  resources :recepcions

  resources :cargos
  get "panel/index"

  root :to => "panel#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :mesas, :concerns => :paginatable
  resources :productos, :concerns => :paginatable

  resources :clientes









end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
	has_many :empleados
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :recepcions, :dependent => :destroy
end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
	validates :Qt_Cantidad, presence: true
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	belongs_to :cargo
	has_many :recepcions
	#validates :
	validates :Nu_Dni, :No_Empleado, :Tx_Direccion, :Co_Departamento, :Co_Provincia, :Co_Distrito, :Tx_Email, :Fe_Nacimiento, :Tx_telefono, :Fl_Sexo, :Fl_EstadoCivil, :Fe_Contrato, :Fe_Culminacion, :Sa_Salario, presence: true
	validates :Nu_Dni, numericality: { only_integer: true }, uniqueness: true, length: { maximum: 8 }, length: { minimum: 8 }
end
	#validates :equipo1, :equipo2, :arbitro, :estadio, presence: true
	#validates :equipo1, :equipo2, numericality: { only_integer: true }
	#validates :arbitro, :estadio, length: { minimum: 4 }

	#validates :nombre, presence: true, length: { in: 2..20 }, uniqueness: true
	#validates :ciudad, presence: true, length: { maximum: 100 }

app/models/mesa.rb
class Mesa < ActiveRecord::Base
	validates :Co_Mesa, :Qt_CantidadSillas, :Nu_Mesa, :Tipo_Mesa, presence: true
	validates :Co_Mesa, uniqueness: true
	validates :Tipo_Mesa, length: { minimum: 3}
	validates :Qt_CantidadSillas, :Nu_Mesa, numericality: { only_integer: true }
	has_many :recepcions, :dependent => :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :categorium
end

app/models/recepcion.rb
class Recepcion < ActiveRecord::Base
	belongs_to :empleado
	belongs_to :cliente
	belongs_to :mesa
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
#  before_action :set_mesa, only: [:doit]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @mesas = Mesa.all
  end

  # GET /orders/doit/1
  # GET /orders/doit/1.json
  def doit
    @categoria = Categorium.all
    @detalles = Detalle.all
    @detalle = Detalle.new
    #@producto = Producto.where(:categoria_id => params[:id])
  end

  def saveDetails
    @detalle = Detalle.new(detalle_params_details)

    respond_to do |format|
      if @detalle.save
        format.js { render action: 'sucessdet', status: :created, location: @detalle }
      #else
        #format.html { render :new }
        #format.json { render json: @detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  #Save Details sucess
  def sucessdet
  end

  def listaproductos
    @producto = Producto.where(:categoria_id => params[:id])
    respond_to do |format|
        format.js
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_mesa      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:Co_Pedido, :Sa_Subtotal, :Sa_Igv, :Sa_Neto)
    end

    def detalle_params_details
      params.require(:detalle).permit(:producto_id, :Qt_Cantidad, :Sa_PrecioUniSol, :Sa_ImporteSol, :orden_id)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/recepcion_helper.rb
module RecepcionHelper
end

app/views/orders/_detail_order.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>

<%= form_for(@detalle, remote: remote, :url =>{ :action => :saveDetails}, html: {role: :form, 'data-model'=> 'detalles'}) do |f| %>
  <% if @detalle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detalle.errors.count, "error") %> prohibited this detalle from being saved:</h2>
      <ul>
      <% @detalle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Producto, class: 'control-label' %> Agregar nombre del producto(tarea)<br>
  </div>

  <div class="form-group">
    <%= f.label :Cantidad_del_producto, class: 'control-label' %><br>
    <%= f.number_field :Qt_Cantidad, class: 'form-control' %>
  </div>

  <%# Added Bootstrap classes %>
  <div class="actions">
    <%= f.submit 'Agregar un detalle al pedido', class: 'btn btn-danger' %>
  </div>

<% end %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Co_Pedido %><br>
    <%= f.text_field :Co_Pedido %>
  </div>
  <div class="field">
    <%= f.label :Sa_Subtotal %><br>
    <%= f.text_field :Sa_Subtotal %>
  </div>
  <div class="field">
    <%= f.label :Sa_Igv %><br>
    <%= f.text_field :Sa_Igv %>
  </div>
  <div class="field">
    <%= f.label :Sa_Neto %><br>
    <%= f.text_field :Sa_Neto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_item_grid.html.erb
<div>
  <div id="items_grid" >
  <table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nombre del producto</th>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
	    <tr>
        <td><%= item.id %></td>
        <td>
          <%= link_to item.No_Producto, '#new_detail_modal', 'data-toggle' => 'modal' %>
        </td>
      </tr>
	<% end %>
  </tbody>
  </table>
  </div>
</div>

app/views/orders/_table_row.html.erb
<tr>
	<td><%= detalles.producto_id %></td>
	<td><%= detalles.Qt_Cantidad %></td>
	<td><%= link_to 'Quitar del pedido', detalles %></td>
	<!--<td><%= link_to 'Edit', edit_detalle_path(detalles) %></td>
	<td><%= link_to 'Destroy', detalles, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
</tr>		

app/views/orders/doit.html.erb
<div class="row">

	<div class="col-md-6">
		<table class="table table-hover table-bordered">
		<thead>
			<th>LISTA DE CATEGORIA</th>
		</thead>
		<tbody>
		<% @categoria.each do |categorium| %>
			<tr>
		        <td><%= link_to categorium.No_Categoria, ajaxorden_path(:id => categorium.id), :remote => true %></td>
	        </tr>
		<% end %>
		</tbody>
		</table>
	</div>

	<div class="col-md-6">
		<div id="resultAjaxListProductos">
			<span class="text-danger">Elige una categoría del lado izquierdo</span>
		</div>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-md-12">
		<table class="table table-hover" id="table-details">
		  <thead>
		    <tr>
		      <th>PRODUCTO</th><th>Cantidad</th><th colspan="3">Operaciones</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @detalles.each do |detail| %>
		      <%= render partial: 'table_row', locals: {detalles: detail} %>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>
<%= javascript_include_tag 'orders/doit' %>

<div class="modal fade" id="new_detail_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Agrega productos al pedido</h4>
      </div>
      <div class="modal-body">
      	<%= render 'detail_order', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar modal</button>
      </div>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Ordenes</h1>

<div style="border-style: double;padding:15px">
  <% @mesas.each do |mesa| %>
      <button onclick="location.href='orders/doit/<%= mesa.id %>'" class="mesas<%= mesa.free %>"><%= mesa.id %></button>
  <% end %>
</div>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nº Pedido</th>
      <th>Mesa</th>
      <th>SubTotal</th>
      <th>IGV</th>
      <th>Importe Neto</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.mesa_id %></td>
        <td><%= order.Sa_Subtotal %></td>
        <td><%= order.Sa_Igv %></td>
        <td><%= order.Sa_Neto %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/listaproductos.js.erb
$("#resultAjaxListProductos").html("<%= escape_javascript(render partial: 'item_grid', locals: { items: @producto } ) %>"); 

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Co pedido:</strong>
  <%= @order.Co_Pedido %>
</p>

<p>
  <strong>Sa subtotal:</strong>
  <%= @order.Sa_Subtotal %>
</p>

<p>
  <strong>Sa igv:</strong>
  <%= @order.Sa_Igv %>
</p>

<p>
  <strong>Sa neto:</strong>
  <%= @order.Sa_Neto %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/sucessdet.js.erb
$('#table-details').append("<%= j render partial: 'table_row', locals: {detalles: @detalle } %>");
$('#new_detail_modal').modal('hide');