config/routes.rb
Rails.application.routes.draw do
  resources :details
  resources :detalles

  get '/orders/doit/:id', to: 'orders#doit', as: 'doit'
  get '/orders/listaproductos/:id', to: 'orders#listaproductos', as: 'listaproductos'
  get '/ajaxorden', to: 'orders#listaproductos', as: 'ajaxorden'
  post '/orders/saveDetails', to: 'orders#saveDetails', as: 'saveDetails'
  resources :orders

  resources :categoria
  resources :empleados
  devise_for :users
  
  get '/recepcions/findCliente/:id', to: 'recepcions#findCliente', as: 'findCliente'
  resources :recepcions

  resources :cargos
  get "panel/index"

  root :to => "panel#index"

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :mesas, :concerns => :paginatable
  resources :productos, :concerns => :paginatable

  resources :clientes









end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
	has_many :empleados
end

app/models/categorium.rb
class Categorium < ActiveRecord::Base
	has_many :productos
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :recepcions, :dependent => :destroy
end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/models/detalle.rb
class Detalle < ActiveRecord::Base
	validates :Qt_Cantidad, presence: true
end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	belongs_to :cargo
	has_many :recepcions
	#validates :
	validates :Nu_Dni, :No_Empleado, :Tx_Direccion, :Co_Departamento, :Co_Provincia, :Co_Distrito, :Tx_Email, :Fe_Nacimiento, :Tx_telefono, :Fl_Sexo, :Fl_EstadoCivil, :Fe_Contrato, :Fe_Culminacion, :Sa_Salario, presence: true
	validates :Nu_Dni, numericality: { only_integer: true }, uniqueness: true, length: { maximum: 8 }, length: { minimum: 8 }
end
	#validates :equipo1, :equipo2, :arbitro, :estadio, presence: true
	#validates :equipo1, :equipo2, numericality: { only_integer: true }
	#validates :arbitro, :estadio, length: { minimum: 4 }

	#validates :nombre, presence: true, length: { in: 2..20 }, uniqueness: true
	#validates :ciudad, presence: true, length: { maximum: 100 }

app/models/mesa.rb
class Mesa < ActiveRecord::Base
	validates :Co_Mesa, :Qt_CantidadSillas, :Nu_Mesa, :Tipo_Mesa, presence: true
	validates :Co_Mesa, uniqueness: true
	validates :Tipo_Mesa, length: { minimum: 3}
	validates :Qt_CantidadSillas, :Nu_Mesa, numericality: { only_integer: true }
	has_many :recepcions, :dependent => :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/producto.rb
class Producto < ActiveRecord::Base
	belongs_to :categorium
end

app/models/recepcion.rb
class Recepcion < ActiveRecord::Base
	belongs_to :empleado
	belongs_to :cliente
	belongs_to :mesa
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.order(:categoria_id).page(params[:page]).per(5)
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:Co_Producto, :No_Producto, :Qt_CostoProducto, :Nu_CantidadProducto, :Fe_MovimientoProducto, :Fe_VencimientoProducto, :categoria_id)
    end
  public
    #METODO PARA OBTENER EL NOMBRE DEL EQUIPO
    def getNameCat(id)
      @cat = Categorium.find(id)
      name = @cat.No_Categoria
      return name
    end
  helper_method :getNameCat
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/detalles_helper.rb
module DetallesHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/recepcion_helper.rb
module RecepcionHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display:none">
    <%= f.label :'Código de producto' %><br>
    <%= f.text_field :Co_Producto %>
  </div>
  <div class="field">
    <%= f.label :'Nombre de producto' %><br>
    <%= f.text_field :No_Producto %>
  </div>
  <div class="field">
    <%= f.label :'Categoría del producto' %><br>
    <%= f.collection_select(:categoria_id, Categorium.all, :id, :No_Categoria, :prompt => 'SELECCIONE CATEGORIA') %>
  </div>
  <div class="field">
    <%= f.label :'Costo de producto' %><br>
    <%= f.text_field :Qt_CostoProducto %>
  </div>
  <div class="field">
    <%= f.label :'Cantidad de producto' %><br>
    <%= f.number_field :Nu_CantidadProducto %>
  </div>
  <div class="field">
    <%= f.label :'Fecha de movimiento de producto' %><br>
    <%= f.date_select :Fe_MovimientoProducto %>
  </div>
  <div class="field">
    <%= f.label :'Fecha de vencimiento de producto' %><br>
    <%= f.date_select :Fe_VencimientoProducto %>
  </div>
  <div class="actions">
    <% if params[:action] == 'new'%>
    <%= f.submit "Crear producto" %>
    <% else %>
    <%= f.submit "Actualizar producto" %>
    <% end %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @producto %> |
<%= link_to 'Regresar', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Productos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre de producto</th>
      <th>Categoría</th>
      <th>Costo de producto</th>
      <th>Cantidad producto</th>
      <th>Fecha de movimiento de producto</th>
      <th>Fecha de vencimiento de sproducto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.No_Producto %></td>
        <td><%= getNameCat(producto.categoria_id) %></td>
        <td><%= producto.Qt_CostoProducto %></td>
        <td><%= producto.Nu_CantidadProducto %></td>
        <td><%= producto.Fe_MovimientoProducto %></td>
        <td><%= producto.Fe_VencimientoProducto %></td>
        <td><%= link_to 'Mostrar', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destruir', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @productos%>
<%= link_to 'Nuevo producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>Nuevo ingreso de Productos</h1>

<%= render 'form' %>

<%= link_to 'Regresar', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código de producto:</strong>
  <%= @producto.Co_Producto %>
</p>

<p>
  <strong>Nombre de producto:</strong>
  <%= @producto.No_Producto %>
</p>

<p>
  <strong>Costo de producto:</strong>
  <%= @producto.Qt_CostoProducto %>
</p>

<p>
  <strong>Cantidad de producto:</strong>
  <%= @producto.Nu_CantidadProducto %>
</p>

<p>
  <strong>Fecha de movimiento de producto:</strong>
  <%= @producto.Fe_MovimientoProducto %>
</p>

<p>
  <strong>Fecha de vencimiento de producto:</strong>
  <%= @producto.Fe_VencimientoProducto %>
</p>

<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Regresar', productos_path %>